### ISSUE TITLE
TODO/FIXME Count 3

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-docs#17]
- [ ] FIXME: Is this an acceptable assumption to make?
       Commit: (cd254df) Ignore OPTIONS errors; typically used for CORS.
       File:  [lib/services.docs.js:215](https://github.com/digitalbazaar/bedrock-docs/blob/master/lib/services.docs.js#L215)
       Manu Sporny commented 4 years ago

  - [ ] FIXME: Race condition - this may be exposed before the documentation is built
       Commit: (e723df9) Update to work with new express routes design.
       File:  [lib/services.docs.js:113](https://github.com/digitalbazaar/bedrock-docs/blob/master/lib/services.docs.js#L113)
       Manu Sporny commented 4 years ago

  - [ ] TODO: if an express 4.x custom router is used via express.Router(),
       Commit: (ef754be) Add support for bedrock-express 0.2.x.
       File:  [lib/services.docs.js:31](https://github.com/digitalbazaar/bedrock-docs/blob/master/lib/services.docs.js#L31)
       Dave Longley commented 5 years ago
